app:
    resource:   "@AppBundle/Controller/"
    type:       annotation

app_taskapi_gettasks:
    pattern:  /api/v1/tasks
    defaults: { _controller: AppBundle:TaskApi:getTasks, _format: ~ }
    requirements:
        _method: GET

app_taskapi_gettask:
    pattern:  /api/v1/tasks/{id}
    defaults: { _controller: AppBundle:TaskApi:getTask, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

app_taskapi_posttasks:
    pattern:  /api/v1/tasks
    defaults: { _controller: AppBundle:TaskApi:postTasks, _format: ~ }
    requirements:
        _method: POST

app_taskapi_puttask:
    pattern:  /api/v1/tasks/{id}
    defaults: { _controller: AppBundle:TaskApi:putTask, _format: ~ }
    requirements:
        _method: PATCH

app_taskapi_delete:
    pattern:  /api/v1/tasks/{id}
    defaults: { _controller: AppBundle:TaskApi:delete, _format: ~ }
    requirements:
        _method: DELETE

NelmioApiDocBundle:
    resource:   "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:       /api/doc

fos_js_routing:
    resource:   "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
